### ISSUE TITLE
Can I use pretrained model for 4K images?

### ISSUE THREAD

**Issue by yr21kim** [zihuazheng/DIP#4]
Hi, thank you for your awesome work!
I tested on images in your repo, and the result was great!

However, when I tried on 4K images, the results were quite off.
Is it because I have to change some parameters for 4K resolution images?
Or should I train the model on 4K image dataset?

**Comment by zihuazheng** [comment]
Because we trained on servers and loaded data remotely from the cloud, our training method may not be suitable for typical users. You can refer to the training method of RAFT, which can also achieve the same results as ours.

**Comment by zihuazheng** [comment]
Due to limitations in the available GPU memory, we did not train our model at resolutions higher than 1K. This makes it difficult to generalize to higher resolutions because they represent larger displacements (or optical flow values) . Therefore, if you want to test the model at 4K and have enough GPU memory, we recommend fine-tuning at a higher resolution. Additionally, incorporating more datasets such as AutoFlow(https://autoflow-google.github.io/) may further improve the model's generalization.

**Comment by zihuazheng** [comment]
You can also try to infer on 1K first, and then use the result of 1K as the initial input to 4K. This might be useful, since 1/16 * 4K, is still a relatively large resolution, the random initialization may be too sparse

**Comment by yr21kim** [comment]
Thank you for your response! I will try fine tuning and using 1K result as initial input.

I got 22~23 sec inference time on 4K image (3840x2160) on 1 A100 gpu. Is this reasonable time? Or should I change any parameters for high resolution images?
